# Generated by Django 4.1.5 on 2023-04-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonDRF", "0002_alter_menuitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
